modLoader="javafml"
loaderVersion="[41,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/ToolBelt/issues"

[[mods]]
modId="noflydimensions"
version="${file.jarVersion}"
displayName="Tool Belt"
description='''
Declutter your inventory of tools
'''
displayURL="https://github.com/gigaherz/ToolBelt"
logoFile="logo.png"
authors="gigaherz"

[[dependencies.noflydimensions]]
   modId="forge"
   mandatory=true
   versionRange="[41.0.94,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.noflydimensions]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19,1.20)"
   ordering="NONE"
   side="BOTH"
[[dependencies.noflydimensions]]
   modId="dragonsurvival"
   mandatory=true
   versionRange="[1.5.57,)"
   ordering="NONE"
   side="BOTH"